### ISSUE TITLE
Enchantments suggestions

### ISSUE THREAD

**Issue by spacecake** [moval0x1/NoDelete#1]
Hello @moval0x1,
Interesting project!

I would suggest few additional features expand into, like:

1. Running without the UI
2. Configure monitored directory's from a list argument  from a given file
3. On delete, trigger an event in Windows Event Log

This could automate and enlarge the scope and usage.
I am only on my second coffee 😇

Keep up the good work!

Kind regards

**Comment by moval0x1** [comment]
Hello @spacecake, I really appreciate your suggestions. They can improve the tool a lot. I'm taking notes about them and will start working on them.

Thanks bro!
